version: '2'
services:
    aics-app:
        image: aics
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aics-mysql:3306/aics?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    aics-mysql:
        extends:
            file: mysql.yml
            service: aics-mysql
